# Generated by Django 5.0.3 on 2024-03-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TZDBErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ErrorDate', models.DateField()),
                ('ErrorMessage', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TZDBTimezone',
            fields=[
                ('CountryCode', models.CharField(max_length=10)),
                ('CountryName', models.CharField(max_length=100)),
                ('ZoneName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('GMTOffset', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ImportDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TZDBZoneDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryName', models.CharField(max_length=100)),
                ('CountryCode', models.CharField(max_length=10)),
                ('ZoneName', models.CharField(max_length=100)),
                ('GMTOffset', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DST', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ZoneStart', models.IntegerField()),
                ('ZoneEnd', models.IntegerField()),
                ('ImportDate', models.DateField()),
            ],
        ),
    ]
